export const PROPERTY_LIST_REQUEST = 'PROPERTY_LIST_REQUEST';
export const PROPERTY_LIST_SUCCESS = 'PROPERTY_LIST_SUCCESS';
export const PROPERTY_LIST_FAIL = 'PROPERTY_LIST_FAIL';

export const PROPERTY_DETAILS_REQUEST = 'PROPERTY_DETAILS_REQUEST';
export const PROPERTY_DETAILS_SUCCESS = 'PROPERTY_DETAILS_SUCCESS';
export const PROPERTY_DETAILS_FAIL = 'PROPERTY_DETAILS_FAIL';

export const PROPERTY_CREATE_REQUEST = 'PROPERTY_CREATE_REQUEST';
export const PROPERTY_CREATE_SUCCESS = 'PROPERTY_CREATE_SUCCESS';
export const PROPERTY_CREATE_FAIL = 'PROPERTY_CREATE_FAIL';